name: Deploy Configuration
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: "Deploy to environment"
    environment: rust1
    runs-on: self-hosted
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host rust1
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_HOST: ${{ secrets.SERVER_HOSTNAME }}
          SSH_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      - name: Put a file on the server
        run: |
          ssh rust1 'echo test >> testfile'